import {
  createEgressPool as baseCreateEgressPool,
  DEFAULT_BLOCKED_STATUSES,
  DEFAULT_EGRESS_BACKGROUND_RESERVE_PER_LANE as DEFAULT_BACKGROUND_RESERVE_PER_LANE,
  DEFAULT_EGRESS_COOLDOWN_MS as DEFAULT_COOLDOWN_MS,
  DEFAULT_EGRESS_EWMA_ALPHA as EWMA_ALPHA,
  DEFAULT_EGRESS_MAX_CONCURRENCY_PER_LANE as DEFAULT_MAX_CONCURRENCY_PER_LANE,
  DEFAULT_EGRESS_MAX_LATENCY_SAMPLE_MS as MAX_LATENCY_SAMPLE_MS,
  DEFAULT_EGRESS_MIN_CONCURRENCY_PER_LANE as DEFAULT_MIN_CONCURRENCY_PER_LANE,
  DEFAULT_EGRESS_SUCCESS_RAMP_AFTER as DEFAULT_SUCCESS_RAMP_AFTER,
  isRetryableStatus as isRetryable,
  isSuccessfulStatus as isSuccess,
  poolError,
  RETRYABLE_STATUSES,
  safeEvent,
} from './http-utils.js';

export {
  isSuccess,
  isRetryable,
  poolError,
  safeEvent,
  DEFAULT_MIN_CONCURRENCY_PER_LANE,
  DEFAULT_MAX_CONCURRENCY_PER_LANE,
  DEFAULT_SUCCESS_RAMP_AFTER,
  DEFAULT_COOLDOWN_MS,
  DEFAULT_BACKGROUND_RESERVE_PER_LANE,
  DEFAULT_BLOCKED_STATUSES,
  EWMA_ALPHA,
  MAX_LATENCY_SAMPLE_MS,
  RETRYABLE_STATUSES,
};

export function createEgressPool(options = {}) {
  return baseCreateEgressPool(options);
}
